# _config.yml

title: Alper Kocatas - Home
description: A simple website hosted on GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site

# Exclude these files and directories from the site
exclude:
  - README.md

# Set the markdown processor
markdown: kramdown

# Include these plugins
plugins:
  - jekyll-feed

# Set the theme for the site (choose a theme supported by GitHub Pages)
theme: jekyll-theme-minimal

# Social media usernames (optional)
twitter_username: kocatasTolga
github_username: alperkocatas

gem "github-pages", group: :jekyll_plugins
